### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by YevhenKovalevskyi** [YevhenKovalevskyi/homepage#7]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by YevhenKovalevskyi** [comment]
Waiting for a comment.

**Comment by volodymyr-kushnir** [comment]
ха! я так і знав, що в цьому моменті ми неправильно пояснили все 😩.
в общєм, по пла-а-а-а-ану студент мав би це зробити сам. але воно вийшло неявно, тому я думаю, що багато хто на цьому і зупиниться на якийсь час. тим не менше, хто в тебе, Трамп? тоді зараз...

**Comment by volodymyr-kushnir** [comment]
💥!
### ― I'm the most successful person ever to run for the presidency, by far. Nobody's ever been more successful than me. I'm the most successful person ever to run. Ross Perot isn't successful like me. Romney ― I have a Gucci store that's worth more than Romney. Sorry losers and haters, but my IQ is one of the highest ― and you all know it! Please don't feel so stupid or insecure, it's not your fault.
